### ISSUE TITLE
Questions about integrating

### ISSUE THREAD

**Issue by zackman0010** [grafana/alloy-remote-config#8]
Hi! I was wondering if there was a place to see an example service that integrates this framework to respond to Alloy? Or if not that, then more documentation on the intended uses of the other APIs.

I assume that GetConfig is the API that Alloy calls to, and so it's expected that the intended config file be returned from there. However, what are the rest of the APIs for? Does Alloy call out to them in any way, or are they optional APIs to build a config management platform for Collector instances? And how do the Pipeline APIs fit in here?

Lastly, does our implementation have to be written with go-connect, or can we use a gRPC library in other languages?

**Comment by tpaschalis** [comment]
Hey @zackman0010 thansk for reaching out and apologies for the belated response!

We have no reference implementation out there yet, but you're right that `GetConfig` is the only RPC that Alloy itself calls.

The rest of the API was a best-effort guesstimation of what other RPCs implementors might need in order to keep track of pipelines (config snippets) and running collectors. I was on the fence but I've come to realize they're more of a distraction so I've opened #9 to minimize the surface area of the API to just what Alloy uses and leave all other details up to each implementation.

> Lastly, does our implementation have to be written with go-connect, or can we use a gRPC library in other languages?

You should be able to use any gRPC library as long as it uses the same protobuf files.

**Comment by oleewere** [comment]
i have created an implementation by using go-connect, see: https://github.com/opsplane-services/alloy-remote-config-server  - seemed like working ok, i also tried to generate grpc code from the proto files and test against those, i got errors in the alloy code with wrong responses, but no problem with referencing this code with go-connect

**Comment by tpaschalis** [comment]
Hey there @oleewere , just caught your response! It's great that you were able to create an implementation! Did it work alright for you? Any comments, remarks, how did you end up using it?

> i got errors in the alloy code with wrong responses

Can you share these errors so we can figure out if there's any bug?

FYI we've updated the RPC with a Register/UnregisterCollector pair of RPCs which we think could be useful.

**Comment by erikbaranowski** [comment]
Closing issue due to staleness
